# -*- coding: utf-8 -*-
"""generate_map

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XsPsSUvqoCdR7cUws7r17b01tGn5kHGx
"""

import pandas as pd
import folium
from sklearn.cluster import KMeans
import os

# 1. Load Data
# Pastikan nama file sesuai dengan yang kamu upload
filename = 'katalog_gempa_v2.tsv'
try:
    df = pd.read_csv(filename, sep='\t')
    # Bersihkan data (ambil kolom penting saja)
    df_clean = df[['latitude', 'longitude', 'magnitude', 'depth']].dropna()

    # Filter data sedikit (opsional, biar tidak terlalu berat di web)
    # Misalnya kita ambil yang magnitudonya di atas 3.0 saja
    df_clean = df_clean[df_clean['magnitude'] >= 3.0]

except FileNotFoundError:
    print("File data tidak ditemukan!")
    exit()

# 2. Proses K-Means (Kita set fix 4 cluster misalnya, karena di statis tidak ada slider)
n_clusters = 4
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
df_clean['cluster'] = kmeans.fit_predict(df_clean[['latitude', 'longitude', 'depth']])

# 3. Buat Peta Folium
# Pusat peta di rata-rata koordinat
m = folium.Map(location=[df_clean['latitude'].mean(), df_clean['longitude'].mean()], zoom_start=5)

colors = ['red', 'blue', 'green', 'purple', 'orange', 'darkred']

for idx, row in df_clean.iterrows():
    cluster_id = int(row['cluster'])
    color_idx = cluster_id % len(colors)

    folium.CircleMarker(
        location=[row['latitude'], row['longitude']],
        radius=row['magnitude'],
        color=colors[color_idx],
        fill=True,
        fill_color=colors[color_idx],
        fill_opacity=0.7,
        popup=f"Mag: {row['magnitude']} | Depth: {row['depth']} km"
    ).add_to(m)

# Tambahkan Judul di peta (HTML hack simple)
title_html = '''
     <h3 align="center" style="font-size:20px"><b>Peta Zonasi Gempa (Hasil Clustering Static)</b></h3>
     '''
m.get_root().html.add_child(folium.Element(title_html))

# 4. Simpan jadi HTML agar bisa dibaca GitHub Pages
if not os.path.exists('public'):
    os.makedirs('public')

m.save('public/index.html')
print("Sukses! File index.html telah dibuat di folder public.")